

python bjob_pcd_mlp_art_committee.py novelty_ClasseA_1024nfft.jbl PCD_Independent/pcdind_cv_ClasseA_fromMat_1024nfft.jbl PCD04_ARTConstructive/art_pcdcons4_cv_ClasseA_fromMat_1024nfft.jbl 0 Teste



