# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_neuralnet', [dirname(__file__)])
        except ImportError:
            import _neuralnet
            return _neuralnet
        if fp is not None:
            try:
                _mod = imp.load_module('_neuralnet', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _neuralnet = swig_import_helper()
    del swig_import_helper
else:
    import _neuralnet
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _neuralnet.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _neuralnet.SwigPyIterator_value(self)
    def incr(self, n = 1): return _neuralnet.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _neuralnet.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _neuralnet.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _neuralnet.SwigPyIterator_equal(self, *args)
    def copy(self): return _neuralnet.SwigPyIterator_copy(self)
    def next(self): return _neuralnet.SwigPyIterator_next(self)
    def __next__(self): return _neuralnet.SwigPyIterator___next__(self)
    def previous(self): return _neuralnet.SwigPyIterator_previous(self)
    def advance(self, *args): return _neuralnet.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _neuralnet.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _neuralnet.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _neuralnet.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _neuralnet.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _neuralnet.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _neuralnet.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _neuralnet.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class RowF(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RowF, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RowF, name)
    __repr__ = _swig_repr
    def iterator(self): return _neuralnet.RowF_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _neuralnet.RowF___nonzero__(self)
    def __bool__(self): return _neuralnet.RowF___bool__(self)
    def __len__(self): return _neuralnet.RowF___len__(self)
    def pop(self): return _neuralnet.RowF_pop(self)
    def __getslice__(self, *args): return _neuralnet.RowF___getslice__(self, *args)
    def __setslice__(self, *args): return _neuralnet.RowF___setslice__(self, *args)
    def __delslice__(self, *args): return _neuralnet.RowF___delslice__(self, *args)
    def __delitem__(self, *args): return _neuralnet.RowF___delitem__(self, *args)
    def __getitem__(self, *args): return _neuralnet.RowF___getitem__(self, *args)
    def __setitem__(self, *args): return _neuralnet.RowF___setitem__(self, *args)
    def append(self, *args): return _neuralnet.RowF_append(self, *args)
    def empty(self): return _neuralnet.RowF_empty(self)
    def size(self): return _neuralnet.RowF_size(self)
    def clear(self): return _neuralnet.RowF_clear(self)
    def swap(self, *args): return _neuralnet.RowF_swap(self, *args)
    def get_allocator(self): return _neuralnet.RowF_get_allocator(self)
    def begin(self): return _neuralnet.RowF_begin(self)
    def end(self): return _neuralnet.RowF_end(self)
    def rbegin(self): return _neuralnet.RowF_rbegin(self)
    def rend(self): return _neuralnet.RowF_rend(self)
    def pop_back(self): return _neuralnet.RowF_pop_back(self)
    def erase(self, *args): return _neuralnet.RowF_erase(self, *args)
    def __init__(self, *args): 
        this = _neuralnet.new_RowF(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _neuralnet.RowF_push_back(self, *args)
    def front(self): return _neuralnet.RowF_front(self)
    def back(self): return _neuralnet.RowF_back(self)
    def assign(self, *args): return _neuralnet.RowF_assign(self, *args)
    def resize(self, *args): return _neuralnet.RowF_resize(self, *args)
    def insert(self, *args): return _neuralnet.RowF_insert(self, *args)
    def reserve(self, *args): return _neuralnet.RowF_reserve(self, *args)
    def capacity(self): return _neuralnet.RowF_capacity(self)
    __swig_destroy__ = _neuralnet.delete_RowF
    __del__ = lambda self : None;
RowF_swigregister = _neuralnet.RowF_swigregister
RowF_swigregister(RowF)

class MatrixF(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MatrixF, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MatrixF, name)
    __repr__ = _swig_repr
    def iterator(self): return _neuralnet.MatrixF_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _neuralnet.MatrixF___nonzero__(self)
    def __bool__(self): return _neuralnet.MatrixF___bool__(self)
    def __len__(self): return _neuralnet.MatrixF___len__(self)
    def pop(self): return _neuralnet.MatrixF_pop(self)
    def __getslice__(self, *args): return _neuralnet.MatrixF___getslice__(self, *args)
    def __setslice__(self, *args): return _neuralnet.MatrixF___setslice__(self, *args)
    def __delslice__(self, *args): return _neuralnet.MatrixF___delslice__(self, *args)
    def __delitem__(self, *args): return _neuralnet.MatrixF___delitem__(self, *args)
    def __getitem__(self, *args): return _neuralnet.MatrixF___getitem__(self, *args)
    def __setitem__(self, *args): return _neuralnet.MatrixF___setitem__(self, *args)
    def append(self, *args): return _neuralnet.MatrixF_append(self, *args)
    def empty(self): return _neuralnet.MatrixF_empty(self)
    def size(self): return _neuralnet.MatrixF_size(self)
    def clear(self): return _neuralnet.MatrixF_clear(self)
    def swap(self, *args): return _neuralnet.MatrixF_swap(self, *args)
    def get_allocator(self): return _neuralnet.MatrixF_get_allocator(self)
    def begin(self): return _neuralnet.MatrixF_begin(self)
    def end(self): return _neuralnet.MatrixF_end(self)
    def rbegin(self): return _neuralnet.MatrixF_rbegin(self)
    def rend(self): return _neuralnet.MatrixF_rend(self)
    def pop_back(self): return _neuralnet.MatrixF_pop_back(self)
    def erase(self, *args): return _neuralnet.MatrixF_erase(self, *args)
    def __init__(self, *args): 
        this = _neuralnet.new_MatrixF(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _neuralnet.MatrixF_push_back(self, *args)
    def front(self): return _neuralnet.MatrixF_front(self)
    def back(self): return _neuralnet.MatrixF_back(self)
    def assign(self, *args): return _neuralnet.MatrixF_assign(self, *args)
    def resize(self, *args): return _neuralnet.MatrixF_resize(self, *args)
    def insert(self, *args): return _neuralnet.MatrixF_insert(self, *args)
    def reserve(self, *args): return _neuralnet.MatrixF_reserve(self, *args)
    def capacity(self): return _neuralnet.MatrixF_capacity(self)
    __swig_destroy__ = _neuralnet.delete_MatrixF
    __del__ = lambda self : None;
MatrixF_swigregister = _neuralnet.MatrixF_swigregister
MatrixF_swigregister(MatrixF)

class RowUI(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RowUI, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RowUI, name)
    __repr__ = _swig_repr
    def iterator(self): return _neuralnet.RowUI_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _neuralnet.RowUI___nonzero__(self)
    def __bool__(self): return _neuralnet.RowUI___bool__(self)
    def __len__(self): return _neuralnet.RowUI___len__(self)
    def pop(self): return _neuralnet.RowUI_pop(self)
    def __getslice__(self, *args): return _neuralnet.RowUI___getslice__(self, *args)
    def __setslice__(self, *args): return _neuralnet.RowUI___setslice__(self, *args)
    def __delslice__(self, *args): return _neuralnet.RowUI___delslice__(self, *args)
    def __delitem__(self, *args): return _neuralnet.RowUI___delitem__(self, *args)
    def __getitem__(self, *args): return _neuralnet.RowUI___getitem__(self, *args)
    def __setitem__(self, *args): return _neuralnet.RowUI___setitem__(self, *args)
    def append(self, *args): return _neuralnet.RowUI_append(self, *args)
    def empty(self): return _neuralnet.RowUI_empty(self)
    def size(self): return _neuralnet.RowUI_size(self)
    def clear(self): return _neuralnet.RowUI_clear(self)
    def swap(self, *args): return _neuralnet.RowUI_swap(self, *args)
    def get_allocator(self): return _neuralnet.RowUI_get_allocator(self)
    def begin(self): return _neuralnet.RowUI_begin(self)
    def end(self): return _neuralnet.RowUI_end(self)
    def rbegin(self): return _neuralnet.RowUI_rbegin(self)
    def rend(self): return _neuralnet.RowUI_rend(self)
    def pop_back(self): return _neuralnet.RowUI_pop_back(self)
    def erase(self, *args): return _neuralnet.RowUI_erase(self, *args)
    def __init__(self, *args): 
        this = _neuralnet.new_RowUI(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _neuralnet.RowUI_push_back(self, *args)
    def front(self): return _neuralnet.RowUI_front(self)
    def back(self): return _neuralnet.RowUI_back(self)
    def assign(self, *args): return _neuralnet.RowUI_assign(self, *args)
    def resize(self, *args): return _neuralnet.RowUI_resize(self, *args)
    def insert(self, *args): return _neuralnet.RowUI_insert(self, *args)
    def reserve(self, *args): return _neuralnet.RowUI_reserve(self, *args)
    def capacity(self): return _neuralnet.RowUI_capacity(self)
    __swig_destroy__ = _neuralnet.delete_RowUI
    __del__ = lambda self : None;
RowUI_swigregister = _neuralnet.RowUI_swigregister
RowUI_swigregister(RowUI)

class MatrixUI(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MatrixUI, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MatrixUI, name)
    __repr__ = _swig_repr
    def iterator(self): return _neuralnet.MatrixUI_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _neuralnet.MatrixUI___nonzero__(self)
    def __bool__(self): return _neuralnet.MatrixUI___bool__(self)
    def __len__(self): return _neuralnet.MatrixUI___len__(self)
    def pop(self): return _neuralnet.MatrixUI_pop(self)
    def __getslice__(self, *args): return _neuralnet.MatrixUI___getslice__(self, *args)
    def __setslice__(self, *args): return _neuralnet.MatrixUI___setslice__(self, *args)
    def __delslice__(self, *args): return _neuralnet.MatrixUI___delslice__(self, *args)
    def __delitem__(self, *args): return _neuralnet.MatrixUI___delitem__(self, *args)
    def __getitem__(self, *args): return _neuralnet.MatrixUI___getitem__(self, *args)
    def __setitem__(self, *args): return _neuralnet.MatrixUI___setitem__(self, *args)
    def append(self, *args): return _neuralnet.MatrixUI_append(self, *args)
    def empty(self): return _neuralnet.MatrixUI_empty(self)
    def size(self): return _neuralnet.MatrixUI_size(self)
    def clear(self): return _neuralnet.MatrixUI_clear(self)
    def swap(self, *args): return _neuralnet.MatrixUI_swap(self, *args)
    def get_allocator(self): return _neuralnet.MatrixUI_get_allocator(self)
    def begin(self): return _neuralnet.MatrixUI_begin(self)
    def end(self): return _neuralnet.MatrixUI_end(self)
    def rbegin(self): return _neuralnet.MatrixUI_rbegin(self)
    def rend(self): return _neuralnet.MatrixUI_rend(self)
    def pop_back(self): return _neuralnet.MatrixUI_pop_back(self)
    def erase(self, *args): return _neuralnet.MatrixUI_erase(self, *args)
    def __init__(self, *args): 
        this = _neuralnet.new_MatrixUI(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _neuralnet.MatrixUI_push_back(self, *args)
    def front(self): return _neuralnet.MatrixUI_front(self)
    def back(self): return _neuralnet.MatrixUI_back(self)
    def assign(self, *args): return _neuralnet.MatrixUI_assign(self, *args)
    def resize(self, *args): return _neuralnet.MatrixUI_resize(self, *args)
    def insert(self, *args): return _neuralnet.MatrixUI_insert(self, *args)
    def reserve(self, *args): return _neuralnet.MatrixUI_reserve(self, *args)
    def capacity(self): return _neuralnet.MatrixUI_capacity(self)
    __swig_destroy__ = _neuralnet.delete_MatrixUI
    __del__ = lambda self : None;
MatrixUI_swigregister = _neuralnet.MatrixUI_swigregister
MatrixUI_swigregister(MatrixUI)

class RowI(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RowI, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RowI, name)
    __repr__ = _swig_repr
    def iterator(self): return _neuralnet.RowI_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _neuralnet.RowI___nonzero__(self)
    def __bool__(self): return _neuralnet.RowI___bool__(self)
    def __len__(self): return _neuralnet.RowI___len__(self)
    def pop(self): return _neuralnet.RowI_pop(self)
    def __getslice__(self, *args): return _neuralnet.RowI___getslice__(self, *args)
    def __setslice__(self, *args): return _neuralnet.RowI___setslice__(self, *args)
    def __delslice__(self, *args): return _neuralnet.RowI___delslice__(self, *args)
    def __delitem__(self, *args): return _neuralnet.RowI___delitem__(self, *args)
    def __getitem__(self, *args): return _neuralnet.RowI___getitem__(self, *args)
    def __setitem__(self, *args): return _neuralnet.RowI___setitem__(self, *args)
    def append(self, *args): return _neuralnet.RowI_append(self, *args)
    def empty(self): return _neuralnet.RowI_empty(self)
    def size(self): return _neuralnet.RowI_size(self)
    def clear(self): return _neuralnet.RowI_clear(self)
    def swap(self, *args): return _neuralnet.RowI_swap(self, *args)
    def get_allocator(self): return _neuralnet.RowI_get_allocator(self)
    def begin(self): return _neuralnet.RowI_begin(self)
    def end(self): return _neuralnet.RowI_end(self)
    def rbegin(self): return _neuralnet.RowI_rbegin(self)
    def rend(self): return _neuralnet.RowI_rend(self)
    def pop_back(self): return _neuralnet.RowI_pop_back(self)
    def erase(self, *args): return _neuralnet.RowI_erase(self, *args)
    def __init__(self, *args): 
        this = _neuralnet.new_RowI(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _neuralnet.RowI_push_back(self, *args)
    def front(self): return _neuralnet.RowI_front(self)
    def back(self): return _neuralnet.RowI_back(self)
    def assign(self, *args): return _neuralnet.RowI_assign(self, *args)
    def resize(self, *args): return _neuralnet.RowI_resize(self, *args)
    def insert(self, *args): return _neuralnet.RowI_insert(self, *args)
    def reserve(self, *args): return _neuralnet.RowI_reserve(self, *args)
    def capacity(self): return _neuralnet.RowI_capacity(self)
    __swig_destroy__ = _neuralnet.delete_RowI
    __del__ = lambda self : None;
RowI_swigregister = _neuralnet.RowI_swigregister
RowI_swigregister(RowI)

class MatrixI(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MatrixI, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MatrixI, name)
    __repr__ = _swig_repr
    def iterator(self): return _neuralnet.MatrixI_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _neuralnet.MatrixI___nonzero__(self)
    def __bool__(self): return _neuralnet.MatrixI___bool__(self)
    def __len__(self): return _neuralnet.MatrixI___len__(self)
    def pop(self): return _neuralnet.MatrixI_pop(self)
    def __getslice__(self, *args): return _neuralnet.MatrixI___getslice__(self, *args)
    def __setslice__(self, *args): return _neuralnet.MatrixI___setslice__(self, *args)
    def __delslice__(self, *args): return _neuralnet.MatrixI___delslice__(self, *args)
    def __delitem__(self, *args): return _neuralnet.MatrixI___delitem__(self, *args)
    def __getitem__(self, *args): return _neuralnet.MatrixI___getitem__(self, *args)
    def __setitem__(self, *args): return _neuralnet.MatrixI___setitem__(self, *args)
    def append(self, *args): return _neuralnet.MatrixI_append(self, *args)
    def empty(self): return _neuralnet.MatrixI_empty(self)
    def size(self): return _neuralnet.MatrixI_size(self)
    def clear(self): return _neuralnet.MatrixI_clear(self)
    def swap(self, *args): return _neuralnet.MatrixI_swap(self, *args)
    def get_allocator(self): return _neuralnet.MatrixI_get_allocator(self)
    def begin(self): return _neuralnet.MatrixI_begin(self)
    def end(self): return _neuralnet.MatrixI_end(self)
    def rbegin(self): return _neuralnet.MatrixI_rbegin(self)
    def rend(self): return _neuralnet.MatrixI_rend(self)
    def pop_back(self): return _neuralnet.MatrixI_pop_back(self)
    def erase(self, *args): return _neuralnet.MatrixI_erase(self, *args)
    def __init__(self, *args): 
        this = _neuralnet.new_MatrixI(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _neuralnet.MatrixI_push_back(self, *args)
    def front(self): return _neuralnet.MatrixI_front(self)
    def back(self): return _neuralnet.MatrixI_back(self)
    def assign(self, *args): return _neuralnet.MatrixI_assign(self, *args)
    def resize(self, *args): return _neuralnet.MatrixI_resize(self, *args)
    def insert(self, *args): return _neuralnet.MatrixI_insert(self, *args)
    def reserve(self, *args): return _neuralnet.MatrixI_reserve(self, *args)
    def capacity(self): return _neuralnet.MatrixI_capacity(self)
    __swig_destroy__ = _neuralnet.delete_MatrixI
    __del__ = lambda self : None;
MatrixI_swigregister = _neuralnet.MatrixI_swigregister
MatrixI_swigregister(MatrixI)

class floatArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, floatArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _neuralnet.new_floatArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _neuralnet.delete_floatArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _neuralnet.floatArray___getitem__(self, *args)
    def __setitem__(self, *args): return _neuralnet.floatArray___setitem__(self, *args)
    def cast(self): return _neuralnet.floatArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _neuralnet.floatArray_frompointer
    if _newclass:frompointer = staticmethod(_neuralnet.floatArray_frompointer)
floatArray_swigregister = _neuralnet.floatArray_swigregister
floatArray_swigregister(floatArray)

def floatArray_frompointer(*args):
  return _neuralnet.floatArray_frompointer(*args)
floatArray_frompointer = _neuralnet.floatArray_frompointer

class NeuralNet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NeuralNet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NeuralNet, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _neuralnet.new_NeuralNet(*args)
        try: self.this.append(this)
        except: self.this = this
    def copy(self, *args): return _neuralnet.NeuralNet_copy(self, *args)
    def merge(self, *args): return _neuralnet.NeuralNet_merge(self, *args)
    def initialize(self, *args): return _neuralnet.NeuralNet_initialize(self, *args)
    def init_weights(self, *args): return _neuralnet.NeuralNet_init_weights(self, *args)
    def feedforward(self, *args): return _neuralnet.NeuralNet_feedforward(self, *args)
    __swig_setmethods__["str_funcs"] = _neuralnet.NeuralNet_str_funcs_set
    __swig_getmethods__["str_funcs"] = _neuralnet.NeuralNet_str_funcs_get
    if _newclass:str_funcs = _swig_property(_neuralnet.NeuralNet_str_funcs_get, _neuralnet.NeuralNet_str_funcs_set)
    __swig_setmethods__["str_nodes"] = _neuralnet.NeuralNet_str_nodes_set
    __swig_getmethods__["str_nodes"] = _neuralnet.NeuralNet_str_nodes_get
    if _newclass:str_nodes = _swig_property(_neuralnet.NeuralNet_str_nodes_get, _neuralnet.NeuralNet_str_nodes_set)
    def _print(self): return _neuralnet.NeuralNet__print(self)
    def print_weights(self): return _neuralnet.NeuralNet_print_weights(self)
    def getNLayers(self): return _neuralnet.NeuralNet_getNLayers(self)
    def getNNodes(self, *args): return _neuralnet.NeuralNet_getNNodes(self, *args)
    def getWeight(self, *args): return _neuralnet.NeuralNet_getWeight(self, *args)
    def getBias(self, *args): return _neuralnet.NeuralNet_getBias(self, *args)
    def getUseWeight(self, *args): return _neuralnet.NeuralNet_getUseWeight(self, *args)
    def getUseBias(self, *args): return _neuralnet.NeuralNet_getUseBias(self, *args)
    def isFrozenNode(self, *args): return _neuralnet.NeuralNet_isFrozenNode(self, *args)
    def setWeight(self, *args): return _neuralnet.NeuralNet_setWeight(self, *args)
    def setBias(self, *args): return _neuralnet.NeuralNet_setBias(self, *args)
    def setUseBias(self, *args): return _neuralnet.NeuralNet_setUseBias(self, *args)
    def setUseWeights(self, *args): return _neuralnet.NeuralNet_setUseWeights(self, *args)
    def disconnectInput(self, *args): return _neuralnet.NeuralNet_disconnectInput(self, *args)
    def setActFunc(self, *args): return _neuralnet.NeuralNet_setActFunc(self, *args)
    def setFrozen(self, *args): return _neuralnet.NeuralNet_setFrozen(self, *args)
    def isUsingBias(self, *args): return _neuralnet.NeuralNet_isUsingBias(self, *args)
    __swig_destroy__ = _neuralnet.delete_NeuralNet
    __del__ = lambda self : None;
NeuralNet_swigregister = _neuralnet.NeuralNet_swigregister
NeuralNet_swigregister(NeuralNet)

class Backpropagation(NeuralNet):
    __swig_setmethods__ = {}
    for _s in [NeuralNet]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Backpropagation, name, value)
    __swig_getmethods__ = {}
    for _s in [NeuralNet]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Backpropagation, name)
    __repr__ = _swig_repr
    __swig_setmethods__["lrn_rate"] = _neuralnet.Backpropagation_lrn_rate_set
    __swig_getmethods__["lrn_rate"] = _neuralnet.Backpropagation_lrn_rate_get
    if _newclass:lrn_rate = _swig_property(_neuralnet.Backpropagation_lrn_rate_get, _neuralnet.Backpropagation_lrn_rate_set)
    __swig_setmethods__["momentum"] = _neuralnet.Backpropagation_momentum_set
    __swig_getmethods__["momentum"] = _neuralnet.Backpropagation_momentum_get
    if _newclass:momentum = _swig_property(_neuralnet.Backpropagation_momentum_get, _neuralnet.Backpropagation_momentum_set)
    def __init__(self, *args): 
        this = _neuralnet.new_Backpropagation(*args)
        try: self.this.append(this)
        except: self.this = this
    def copy(self, *args): return _neuralnet.Backpropagation_copy(self, *args)
    def _print(self): return _neuralnet.Backpropagation__print(self)
    __swig_destroy__ = _neuralnet.delete_Backpropagation
    __del__ = lambda self : None;
Backpropagation_swigregister = _neuralnet.Backpropagation_swigregister
Backpropagation_swigregister(Backpropagation)

class RProp(Backpropagation):
    __swig_setmethods__ = {}
    for _s in [Backpropagation]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, RProp, name, value)
    __swig_getmethods__ = {}
    for _s in [Backpropagation]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, RProp, name)
    __repr__ = _swig_repr
    __swig_setmethods__["delta_max"] = _neuralnet.RProp_delta_max_set
    __swig_getmethods__["delta_max"] = _neuralnet.RProp_delta_max_get
    if _newclass:delta_max = _swig_property(_neuralnet.RProp_delta_max_get, _neuralnet.RProp_delta_max_set)
    __swig_setmethods__["delta_min"] = _neuralnet.RProp_delta_min_set
    __swig_getmethods__["delta_min"] = _neuralnet.RProp_delta_min_get
    if _newclass:delta_min = _swig_property(_neuralnet.RProp_delta_min_get, _neuralnet.RProp_delta_min_set)
    __swig_setmethods__["inc_eta"] = _neuralnet.RProp_inc_eta_set
    __swig_getmethods__["inc_eta"] = _neuralnet.RProp_inc_eta_get
    if _newclass:inc_eta = _swig_property(_neuralnet.RProp_inc_eta_get, _neuralnet.RProp_inc_eta_set)
    __swig_setmethods__["dec_eta"] = _neuralnet.RProp_dec_eta_set
    __swig_getmethods__["dec_eta"] = _neuralnet.RProp_dec_eta_get
    if _newclass:dec_eta = _swig_property(_neuralnet.RProp_dec_eta_get, _neuralnet.RProp_dec_eta_set)
    __swig_setmethods__["init_eta"] = _neuralnet.RProp_init_eta_set
    __swig_getmethods__["init_eta"] = _neuralnet.RProp_init_eta_get
    if _newclass:init_eta = _swig_property(_neuralnet.RProp_init_eta_get, _neuralnet.RProp_init_eta_set)
    def __init__(self, *args): 
        this = _neuralnet.new_RProp(*args)
        try: self.this.append(this)
        except: self.this = this
    def copy(self, *args): return _neuralnet.RProp_copy(self, *args)
    def _print(self): return _neuralnet.RProp__print(self)
    __swig_destroy__ = _neuralnet.delete_RProp
    __del__ = lambda self : None;
RProp_swigregister = _neuralnet.RProp_swigregister
RProp_swigregister(RProp)

class IOMgr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IOMgr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IOMgr, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _neuralnet.new_IOMgr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _neuralnet.delete_IOMgr
    __del__ = lambda self : None;
    def trn_size(self): return _neuralnet.IOMgr_trn_size(self)
    def val_size(self): return _neuralnet.IOMgr_val_size(self)
    def tst_size(self): return _neuralnet.IOMgr_tst_size(self)
    def shuffle(self): return _neuralnet.IOMgr_shuffle(self)
    def data(self): return _neuralnet.IOMgr_data(self)
    def target(self): return _neuralnet.IOMgr_target(self)
    def set_trn(self, *args): return _neuralnet.IOMgr_set_trn(self, *args)
    def set_val(self, *args): return _neuralnet.IOMgr_set_val(self, *args)
    def set_tst(self, *args): return _neuralnet.IOMgr_set_tst(self, *args)
    def get_trn(self): return _neuralnet.IOMgr_get_trn(self)
    def get_val(self): return _neuralnet.IOMgr_get_val(self)
    def get_tst(self): return _neuralnet.IOMgr_get_tst(self)
    __swig_setmethods__["in_dim"] = _neuralnet.IOMgr_in_dim_set
    __swig_getmethods__["in_dim"] = _neuralnet.IOMgr_in_dim_get
    if _newclass:in_dim = _swig_property(_neuralnet.IOMgr_in_dim_get, _neuralnet.IOMgr_in_dim_set)
    __swig_setmethods__["out_dim"] = _neuralnet.IOMgr_out_dim_set
    __swig_getmethods__["out_dim"] = _neuralnet.IOMgr_out_dim_get
    if _newclass:out_dim = _swig_property(_neuralnet.IOMgr_out_dim_get, _neuralnet.IOMgr_out_dim_set)
    __swig_setmethods__["evt_dim"] = _neuralnet.IOMgr_evt_dim_set
    __swig_getmethods__["evt_dim"] = _neuralnet.IOMgr_evt_dim_get
    if _newclass:evt_dim = _swig_property(_neuralnet.IOMgr_evt_dim_get, _neuralnet.IOMgr_evt_dim_set)
    def initialize(self, *args): return _neuralnet.IOMgr_initialize(self, *args)
IOMgr_swigregister = _neuralnet.IOMgr_swigregister
IOMgr_swigregister(IOMgr)

class TrnInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TrnInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TrnInfo, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _neuralnet.new_TrnInfo(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["epoch"] = _neuralnet.TrnInfo_epoch_set
    __swig_getmethods__["epoch"] = _neuralnet.TrnInfo_epoch_get
    if _newclass:epoch = _swig_property(_neuralnet.TrnInfo_epoch_get, _neuralnet.TrnInfo_epoch_set)
    __swig_setmethods__["mse_trn"] = _neuralnet.TrnInfo_mse_trn_set
    __swig_getmethods__["mse_trn"] = _neuralnet.TrnInfo_mse_trn_get
    if _newclass:mse_trn = _swig_property(_neuralnet.TrnInfo_mse_trn_get, _neuralnet.TrnInfo_mse_trn_set)
    __swig_setmethods__["mse_val"] = _neuralnet.TrnInfo_mse_val_set
    __swig_getmethods__["mse_val"] = _neuralnet.TrnInfo_mse_val_get
    if _newclass:mse_val = _swig_property(_neuralnet.TrnInfo_mse_val_get, _neuralnet.TrnInfo_mse_val_set)
    __swig_setmethods__["mse_tst"] = _neuralnet.TrnInfo_mse_tst_set
    __swig_getmethods__["mse_tst"] = _neuralnet.TrnInfo_mse_tst_get
    if _newclass:mse_tst = _swig_property(_neuralnet.TrnInfo_mse_tst_get, _neuralnet.TrnInfo_mse_tst_set)
    __swig_setmethods__["bst_epoch"] = _neuralnet.TrnInfo_bst_epoch_set
    __swig_getmethods__["bst_epoch"] = _neuralnet.TrnInfo_bst_epoch_get
    if _newclass:bst_epoch = _swig_property(_neuralnet.TrnInfo_bst_epoch_get, _neuralnet.TrnInfo_bst_epoch_set)
    __swig_setmethods__["perfType"] = _neuralnet.TrnInfo_perfType_set
    __swig_getmethods__["perfType"] = _neuralnet.TrnInfo_perfType_get
    if _newclass:perfType = _swig_property(_neuralnet.TrnInfo_perfType_get, _neuralnet.TrnInfo_perfType_set)
    def is_better(self, *args): return _neuralnet.TrnInfo_is_better(self, *args)
    def performance(self, perf = ""): return _neuralnet.TrnInfo_performance(self, perf)
    def getNVar(self): return _neuralnet.TrnInfo_getNVar(self)
    def getVarAddr(self, *args): return _neuralnet.TrnInfo_getVarAddr(self, *args)
    def getVarName(self, *args): return _neuralnet.TrnInfo_getVarName(self, *args)
    __swig_destroy__ = _neuralnet.delete_TrnInfo
    __del__ = lambda self : None;
TrnInfo_swigregister = _neuralnet.TrnInfo_swigregister
TrnInfo_swigregister(TrnInfo)

class TrnInfo_Pattern(TrnInfo):
    __swig_setmethods__ = {}
    for _s in [TrnInfo]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TrnInfo_Pattern, name, value)
    __swig_getmethods__ = {}
    for _s in [TrnInfo]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TrnInfo_Pattern, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _neuralnet.new_TrnInfo_Pattern(*args)
        try: self.this.append(this)
        except: self.this = this
    def copy(self, *args): return _neuralnet.TrnInfo_Pattern_copy(self, *args)
    def performance(self, perf = ""): return _neuralnet.TrnInfo_Pattern_performance(self, perf)
    __swig_setmethods__["mse_trn_c"] = _neuralnet.TrnInfo_Pattern_mse_trn_c_set
    __swig_getmethods__["mse_trn_c"] = _neuralnet.TrnInfo_Pattern_mse_trn_c_get
    if _newclass:mse_trn_c = _swig_property(_neuralnet.TrnInfo_Pattern_mse_trn_c_get, _neuralnet.TrnInfo_Pattern_mse_trn_c_set)
    __swig_setmethods__["mse_val_c"] = _neuralnet.TrnInfo_Pattern_mse_val_c_set
    __swig_getmethods__["mse_val_c"] = _neuralnet.TrnInfo_Pattern_mse_val_c_get
    if _newclass:mse_val_c = _swig_property(_neuralnet.TrnInfo_Pattern_mse_val_c_get, _neuralnet.TrnInfo_Pattern_mse_val_c_set)
    __swig_setmethods__["mse_tst_c"] = _neuralnet.TrnInfo_Pattern_mse_tst_c_set
    __swig_getmethods__["mse_tst_c"] = _neuralnet.TrnInfo_Pattern_mse_tst_c_get
    if _newclass:mse_tst_c = _swig_property(_neuralnet.TrnInfo_Pattern_mse_tst_c_get, _neuralnet.TrnInfo_Pattern_mse_tst_c_set)
    __swig_setmethods__["tot_trn"] = _neuralnet.TrnInfo_Pattern_tot_trn_set
    __swig_getmethods__["tot_trn"] = _neuralnet.TrnInfo_Pattern_tot_trn_get
    if _newclass:tot_trn = _swig_property(_neuralnet.TrnInfo_Pattern_tot_trn_get, _neuralnet.TrnInfo_Pattern_tot_trn_set)
    __swig_setmethods__["tot_val"] = _neuralnet.TrnInfo_Pattern_tot_val_set
    __swig_getmethods__["tot_val"] = _neuralnet.TrnInfo_Pattern_tot_val_get
    if _newclass:tot_val = _swig_property(_neuralnet.TrnInfo_Pattern_tot_val_get, _neuralnet.TrnInfo_Pattern_tot_val_set)
    __swig_setmethods__["tot_tst"] = _neuralnet.TrnInfo_Pattern_tot_tst_set
    __swig_getmethods__["tot_tst"] = _neuralnet.TrnInfo_Pattern_tot_tst_get
    if _newclass:tot_tst = _swig_property(_neuralnet.TrnInfo_Pattern_tot_tst_get, _neuralnet.TrnInfo_Pattern_tot_tst_set)
    __swig_setmethods__["sp_trn"] = _neuralnet.TrnInfo_Pattern_sp_trn_set
    __swig_getmethods__["sp_trn"] = _neuralnet.TrnInfo_Pattern_sp_trn_get
    if _newclass:sp_trn = _swig_property(_neuralnet.TrnInfo_Pattern_sp_trn_get, _neuralnet.TrnInfo_Pattern_sp_trn_set)
    __swig_setmethods__["sp_val"] = _neuralnet.TrnInfo_Pattern_sp_val_set
    __swig_getmethods__["sp_val"] = _neuralnet.TrnInfo_Pattern_sp_val_get
    if _newclass:sp_val = _swig_property(_neuralnet.TrnInfo_Pattern_sp_val_get, _neuralnet.TrnInfo_Pattern_sp_val_set)
    __swig_setmethods__["sp_tst"] = _neuralnet.TrnInfo_Pattern_sp_tst_set
    __swig_getmethods__["sp_tst"] = _neuralnet.TrnInfo_Pattern_sp_tst_get
    if _newclass:sp_tst = _swig_property(_neuralnet.TrnInfo_Pattern_sp_tst_get, _neuralnet.TrnInfo_Pattern_sp_tst_set)
    __swig_setmethods__["eff_trn"] = _neuralnet.TrnInfo_Pattern_eff_trn_set
    __swig_getmethods__["eff_trn"] = _neuralnet.TrnInfo_Pattern_eff_trn_get
    if _newclass:eff_trn = _swig_property(_neuralnet.TrnInfo_Pattern_eff_trn_get, _neuralnet.TrnInfo_Pattern_eff_trn_set)
    __swig_setmethods__["eff_val"] = _neuralnet.TrnInfo_Pattern_eff_val_set
    __swig_getmethods__["eff_val"] = _neuralnet.TrnInfo_Pattern_eff_val_get
    if _newclass:eff_val = _swig_property(_neuralnet.TrnInfo_Pattern_eff_val_get, _neuralnet.TrnInfo_Pattern_eff_val_set)
    __swig_setmethods__["eff_tst"] = _neuralnet.TrnInfo_Pattern_eff_tst_set
    __swig_getmethods__["eff_tst"] = _neuralnet.TrnInfo_Pattern_eff_tst_get
    if _newclass:eff_tst = _swig_property(_neuralnet.TrnInfo_Pattern_eff_tst_get, _neuralnet.TrnInfo_Pattern_eff_tst_set)
    __swig_setmethods__["fa_trn"] = _neuralnet.TrnInfo_Pattern_fa_trn_set
    __swig_getmethods__["fa_trn"] = _neuralnet.TrnInfo_Pattern_fa_trn_get
    if _newclass:fa_trn = _swig_property(_neuralnet.TrnInfo_Pattern_fa_trn_get, _neuralnet.TrnInfo_Pattern_fa_trn_set)
    __swig_setmethods__["fa_val"] = _neuralnet.TrnInfo_Pattern_fa_val_set
    __swig_getmethods__["fa_val"] = _neuralnet.TrnInfo_Pattern_fa_val_get
    if _newclass:fa_val = _swig_property(_neuralnet.TrnInfo_Pattern_fa_val_get, _neuralnet.TrnInfo_Pattern_fa_val_set)
    __swig_setmethods__["fa_tst"] = _neuralnet.TrnInfo_Pattern_fa_tst_set
    __swig_getmethods__["fa_tst"] = _neuralnet.TrnInfo_Pattern_fa_tst_get
    if _newclass:fa_tst = _swig_property(_neuralnet.TrnInfo_Pattern_fa_tst_get, _neuralnet.TrnInfo_Pattern_fa_tst_set)
    __swig_destroy__ = _neuralnet.delete_TrnInfo_Pattern
    __del__ = lambda self : None;
TrnInfo_Pattern_swigregister = _neuralnet.TrnInfo_Pattern_swigregister
TrnInfo_Pattern_swigregister(TrnInfo_Pattern)

class Trainbp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Trainbp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Trainbp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _neuralnet.new_Trainbp()
        try: self.this.append(this)
        except: self.this = this
    def initialize(self): return _neuralnet.Trainbp_initialize(self)
    def train(self): return _neuralnet.Trainbp_train(self)
    __swig_setmethods__["fbatch"] = _neuralnet.Trainbp_fbatch_set
    __swig_getmethods__["fbatch"] = _neuralnet.Trainbp_fbatch_get
    if _newclass:fbatch = _swig_property(_neuralnet.Trainbp_fbatch_get, _neuralnet.Trainbp_fbatch_set)
    __swig_setmethods__["nshow"] = _neuralnet.Trainbp_nshow_set
    __swig_getmethods__["nshow"] = _neuralnet.Trainbp_nshow_get
    if _newclass:nshow = _swig_property(_neuralnet.Trainbp_nshow_get, _neuralnet.Trainbp_nshow_set)
    __swig_setmethods__["nepochs"] = _neuralnet.Trainbp_nepochs_set
    __swig_getmethods__["nepochs"] = _neuralnet.Trainbp_nepochs_get
    if _newclass:nepochs = _swig_property(_neuralnet.Trainbp_nepochs_get, _neuralnet.Trainbp_nepochs_set)
    __swig_setmethods__["min_epochs"] = _neuralnet.Trainbp_min_epochs_set
    __swig_getmethods__["min_epochs"] = _neuralnet.Trainbp_min_epochs_get
    if _newclass:min_epochs = _swig_property(_neuralnet.Trainbp_min_epochs_get, _neuralnet.Trainbp_min_epochs_set)
    __swig_setmethods__["goal"] = _neuralnet.Trainbp_goal_set
    __swig_getmethods__["goal"] = _neuralnet.Trainbp_goal_get
    if _newclass:goal = _swig_property(_neuralnet.Trainbp_goal_get, _neuralnet.Trainbp_goal_set)
    __swig_setmethods__["max_fail"] = _neuralnet.Trainbp_max_fail_set
    __swig_getmethods__["max_fail"] = _neuralnet.Trainbp_max_fail_get
    if _newclass:max_fail = _swig_property(_neuralnet.Trainbp_max_fail_get, _neuralnet.Trainbp_max_fail_set)
    __swig_setmethods__["net_task"] = _neuralnet.Trainbp_net_task_set
    __swig_getmethods__["net_task"] = _neuralnet.Trainbp_net_task_get
    if _newclass:net_task = _swig_property(_neuralnet.Trainbp_net_task_get, _neuralnet.Trainbp_net_task_set)
    def set_net(self, *args): return _neuralnet.Trainbp_set_net(self, *args)
    def get_net(self): return _neuralnet.Trainbp_get_net(self)
    def get_trninfo(self): return _neuralnet.Trainbp_get_trninfo(self)
    def set_iomgr(self, *args): return _neuralnet.Trainbp_set_iomgr(self, *args)
    def get_iomgr(self): return _neuralnet.Trainbp_get_iomgr(self)
    __swig_destroy__ = _neuralnet.delete_Trainbp
    __del__ = lambda self : None;
Trainbp_swigregister = _neuralnet.Trainbp_swigregister
Trainbp_swigregister(Trainbp)

# This file is compatible with both classic and new-style classes.


